test_that("foldchange works with character group", {
    genes = sample(rownames(scdata), 1)
    cells = sample(colnames(scdata), 10) 
    scdata = rowcenter(scdata[genes, , drop = F])
    c(m1,m2) %<-% split_matrix(scdata, cells)
    ref = rowMeans(m1) - rowMeans(m2)
    class(ref) = c("dea.numeric.lfc", class(ref))
    res = dea(scdata, cells, lfc = NULL, p = NULL, return.val = 'lfc')
    expect_equal(res, ref)
})
